apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: pvc-notes-app
  namespace: notes-app

spec: 
 storageClassName: local-storage
 accessModes:
 - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi 
